### ISSUE TITLE
Error under Python 3.5

### ISSUE THREAD

**Issue by ilevantis** [hotdogee/gff3-py#3]
when trying to use .parse on a normal gff file under Python 3.5 I get this:

```
gff.parse(gff_file)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-3986eab23c03> in <module>()
----> 1 gff.parse(gff_file)

/home/ilya/miniconda2/envs/stdsci/lib/python3.5/site-packages/gff3/gff3.py in parse(self, gff_file, strict)
    441             if line_strip != line_raw[:len(line_strip)]:
    442                 self.add_line_error(line_data, {'message': 'White chars not allowed at the start of a line', 'error_type': 'FORMAT', 'location': ''})
--> 443             if current_line_num == 1 and not line_strip.startswith('##gff-version'):
    444                 self.add_line_error(line_data, {'message': '"##gff-version" missing from the first line', 'error_type': 'FORMAT', 'location': ''})
    445             if len(line_strip) == 0:

TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by Allcor** [comment]
Seems to be caused by opening the file with binary mode. Will have to make the search string binary as well. 

ether with `b'##gff-version'` but this was added in Python 2.6. If it needs to be competible with older vertions you could try `'##gff-version'.encode('latin1')`

**Comment by john-theo** [comment]
Same problem in python 3.7

**Comment by hsiaoyi0504** [comment]
@John-Theo Would you mind provide us a minimum example?

**Comment by ipilizota** [comment]
Hi 🙂 
I installed `gff3 1.0.0` today and I'm getting the following error in `Python 3.7.6`:
```
>>> gff.parse(file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hps/software/users/ensembl/compara/shared/pyenv/versions/ip_benchmark3.9/lib/python3.9/site-packages/gff3/gff3.py", line 443, in parse
    if current_line_num == 1 and not line_strip.startswith('##gff-version'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
The first line in the file is `##gff-version 3`.

**Comment by hsiaoyi0504** [comment]
@ipilizota I can't reproduce your error. Could you also try to install the new 1.0.1 version?

**Comment by ipilizota** [comment]
Hi @hsiaoyi0504 🙂  
Thank you very much for your speedy reaction - that helped! 
Have a nice weekend 🙂
